language: python

python:
  - "3.5"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - python -m pytest --cov simple_accounting -v --pep8 --cov-report term-missing

after_success:
    - coveralls